FROM amazoncorretto:21

WORKDIR /

ARG EXPIRATION_TIME
ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST

ENV EXPIRATION_TIME=${EXPIRATION_TIME}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}

COPY /target/lc-kainosjobs-back-1.0-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java", "-jar", "lc-kainosjobs-back-1.0-SNAPSHOT.jar", "server"]